### ISSUE TITLE
Roslaunch motion_control motion_control.launch produces an error

### ISSUE THREAD

**Issue by JauriG** [synapticon/ros_ethercat_igh#4]
The crash comes after the command : `mcx::log::Module logger(path_log);`

The launch command outputs :

setting /run_id to 36355bac-14d8-11e9-a3b1-001500cbe25b
process[rosout-1]: started with pid [8208]
started core service [/rosout]
process[ros_ethercat_server-2]: started with pid [8211]
2019-00-10 14:04:07.312 [ERROR] Failed to configure malloc behavior
[ WARN] [1547125447.312353955]: Run
[ros_ethercat_server-2] process has died [pid 8211, exit code -11, cmd /home/synapticon/catkin_ws/devel/lib/ethercat_master/ethercat_master_server __name:=ros_ethercat_server __log:=/home/synapticon/.ros/log/36355bac-14d8-11e9-a3b1-001500cbe25b/ros_ethercat_server-2.log].
log file: /home/synapticon/.ros/log/36355bac-14d8-11e9-a3b1-001500cbe25b/ros_ethercat_server-2*.log

**Comment by vtretyakov** [comment]
@JauriG could you describe your slave devices configuration, i.e., which devices are connected? Also which ROS version is used?

**Comment by JauriG** [comment]
The error came from the fact that the pdo.xml file still had two drives defined, when I had only one connected. 
Once the second configuration has been erased, the program worked as intended. The issue is now solved
