### ISSUE TITLE
err when run $ catkin build

### ISSUE THREAD

**Issue by gyhg1206** [synapticon/ros_ethercat_igh#5]
Errors     << ethercat_master:make /home/guo/catkin_ws/logs/ethercat_master/build.make.003.log                                    
In file included from /usr/include/mcx/mcx_core.h:27:0,
                 from /home/guo/catkin_ws/src/ros_ethercat_igh/ethercat_master/src/control/Drive.h:43,
                 from /home/guo/catkin_ws/src/ros_ethercat_igh/ethercat_master/src/control/Drive.cpp:40:
/usr/include/mcx/cm_reqrep.h:105:29: error: ‘nn_sock_cb’ has not been declared
   static void onSocketEvent(nn_sock_cb data, void* obj);

..................................................

/usr/include/mcx/cm_reqrep.h:149:31: error: template argument 1 is invalid
   utils::MPMC_Queue<nn_sock_cb> event_queue_{SOCKET_EVENT_QUEUE};

..................................................

make[2]: *** [CMakeFiles/ethercat_master_server.dir/src/control/Drive.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/ethercat_master_server.dir/src/control/DigitalIO.cpp.o] Error 1
make[2]: *** [CMakeFiles/ethercat_master_server.dir/src/main.cpp.o] Error 1
make[2]: *** [CMakeFiles/ethercat_master_server.dir/src/control/MainControlLoop.cpp.o] Error 1
make[1]: *** [CMakeFiles/ethercat_master_server.dir/all] Error 2
make: *** [all] Error 2

Failed     << ethercat_master:make                 [ Exited with code 2 ]                                                         
Failed    <<< ethercat_master                      [ 6.1 seconds ]

**Comment by gyhg1206** [comment]
The link for the package nanomsg1.1.4-Linux.deb on the wiki section is inavailable，so I got a standard one，but it seems can't work.

**Comment by zakharov** [comment]
Please try to reinstall nanomsg from our repository, I fixed broken link: 
https://git.vectioneer.com/pub/motorcortex-dist

**Comment by gyhg1206** [comment]
@zakharov Thank you, I reinstalled nanomsg from your repository, it works well.
